# pyscript.pyi - Type stub file for IDE autocompletion
from typing import Optional, Tuple, Any, Callable, Dict, List, Union

class PyScript:
    def __init__(self, clicker_thread: Any, script_engine: Any) -> None: ...
    
    def click(self, x: Optional[int] = None, y: Optional[int] = None, 
              button: str = 'left', double: bool = False) -> None: ...
    
    def move(self, x: int, y: int, duration: Optional[float] = None) -> None: ...
    
    def wait(self, seconds: float) -> None: ...
    
    def get_position(self) -> Tuple[int, int]: ...
    
    def log(self, message: str, level: Optional[str] = None) -> None: ...
    
    def stop(self) -> None: ...
    
    def is_running(self) -> bool: ...
    
    def on(self, event_name: str, callback: Callable) -> None: ...
    
    def emit(self, event_name: str, data: Any = None) -> None: ...
    
    def get_mouse_state(self) -> Dict[str, Any]: ...
    
    def is_button_pressed(self, button: str = 'left') -> bool: ...
    
    def get_button_state(self) -> Dict[str, bool]: ...
    
    def get_mouse_position(self) -> Tuple[int, int]: ...
    
    def get_last_click_info(self) -> Optional[Tuple[float, str]]: ...
    
    def drag_to(self, x: int, y: int, duration: Optional[float] = None, 
                button: str = 'left') -> None: ...
    
    def mouse_down(self, button: str = 'left', x: Optional[int] = None, 
                   y: Optional[int] = None) -> None: ...
    
    def mouse_up(self, button: str = 'left', x: Optional[int] = None, 
                 y: Optional[int] = None) -> None: ...
    
    def is_dragging(self) -> bool: ...
    
    def get_drag_info(self) -> Optional[Dict[str, Any]]: ...
    
    def mouse_scroll(self, clicks: int, x: Optional[int] = None, 
                     y: Optional[int] = None) -> None: ...
    
    def wait_for_button_press(self, button: str = 'left', 
                              timeout: Optional[float] = None) -> bool: ...
    
    def wait_for_button_release(self, button: str = 'left', 
                                timeout: Optional[float] = None) -> bool: ...